[pytest]
filterwarnings =
    ignore:.*asyncio\.iscoroutinefunction.*:DeprecationWarning
    ignore:.*asyncio\.iscoroutinefunction.*:DeprecationWarning:fastapi\..*
    ignore:.*asyncio\.iscoroutinefunction.*:DeprecationWarning:starlette\..*
