# Lightweight “life event” catalog.
# Later you can randomize events each semester and apply deltas to player.

LIFE_EVENTS = [
    {
        "id": "surprise_quiz",
        "label": "Surprise Quiz Week",
        "stress_delta": 8.0,
        "money_delta": 0.0,
        "happiness_delta": -4.0,
        "weight": 1.0,
    },
    {
        "id": "friend_support",
        "label": "Friends Night & Support",
        "stress_delta": -10.0,
        "money_delta": -40.0,
        "happiness_delta": 10.0,
        "weight": 0.9,
    },
    {
        "id": "rent_increase",
        "label": "Rent Increase",
        "stress_delta": 12.0,
        "money_delta": -100.0,
        "happiness_delta": -5.0,
        "weight": 0.7,
    },
    {
        "id": "scholarship_bonus",
        "label": "Extra Scholarship Grant",
        "stress_delta": -6.0,
        "money_delta": 500.0,
        "happiness_delta": 6.0,
        "weight": 0.4,
    },
    # ===== HEALTH-RELATED EVENTS =====
    {
        "id": "got_sick",
        "label": "Caught a Cold",
        "stress_delta": 8.0,
        "money_delta": -150.0,
        "happiness_delta": -8.0,
        "health_delta": -15.0,
        "weight": 0.20,
    },
    {
        "id": "injury_accident",
        "label": "Accident! Minor Injury",
        "stress_delta": 15.0,
        "money_delta": -300.0,
        "happiness_delta": -12.0,
        "health_delta": -25.0,
        "weight": 0.08,
    },
    {
        "id": "good_health_week",
        "label": "Great Health Week",
        "stress_delta": -8.0,
        "money_delta": 0.0,
        "happiness_delta": 8.0,
        "health_delta": 15.0,
        "weight": 0.15,
    },
    {
        "id": "insomnia_stress",
        "label": "Can't Sleep - Too Much Stress",
        "stress_delta": 12.0,
        "money_delta": 0.0,
        "happiness_delta": -10.0,
        "health_delta": -10.0,
        "weight": 0.18,
    },
    {
        "id": "mental_health_crisis",
        "label": "Mental Health Struggle",
        "stress_delta": 20.0,
        "money_delta": -100.0,
        "happiness_delta": -20.0,
        "health_delta": -20.0,
        "mental_health_delta": -15.0,
        "weight": 0.12,
    },
    {
        "id": "workout_boost",
        "label": "Great Workout & Endorphins!",
        "stress_delta": -12.0,
        "money_delta": 0.0,
        "happiness_delta": 10.0,
        "health_delta": 12.0,
        "weight": 0.14,
    },
    {
        "id": "sleep_recovery",
        "label": "Caught Up on Sleep!",
        "stress_delta": -8.0,
        "money_delta": 0.0,
        "happiness_delta": 8.0,
        "health_delta": 10.0,
        "weight": 0.16,
    },
]
