from __future__ import annotations

from pathlib import Path
from typing import Iterable

ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / "DOCUMENTATION_INDEX.md"

EXCLUDE_DIRS = {
    ".git",
    ".venv",
    ".pytest_cache",
    "__pycache__",
    "node_modules",
    "dist",
    ".vscode",
    ".idea",
}


def rel_md_files() -> list[Path]:
    files: list[Path] = []
    for p in ROOT.rglob("*.md"):
        rel = p.relative_to(ROOT)
        if any(part in EXCLUDE_DIRS for part in rel.parts):
            continue
        if rel == Path("DOCUMENTATION_INDEX.md"):
            continue
        files.append(rel)
    return sorted(files, key=lambda x: str(x).lower())


def only_top_level(files: Iterable[Path]) -> list[Path]:
    return [f for f in files if len(f.parts) == 1]


def in_prefix(files: Iterable[Path], prefix: str) -> list[Path]:
    return [f for f in files if str(f).startswith(prefix + "/")]


def in_exact_dirs(files: Iterable[Path], dirs: set[str]) -> list[Path]:
    return [f for f in files if len(f.parts) >= 2 and f.parts[0] in dirs]


def to_md_list(items: list[Path]) -> str:
    if not items:
        return "- _None found_\n"
    return "".join(f"- [{p}]({p.as_posix()})\n" for p in items)


def render(files: list[Path]) -> str:
    top_level = only_top_level(files)

    start_here_priority = [
        Path("START_HERE.md"),
        Path("QUICKSTART.md"),
        Path("GETTING_STARTED.md"),
        Path("HOW_TO_RUN.md"),
    ]
    start_here = [p for p in start_here_priority if p in top_level]

    core_priority = [
        Path("README.md"),
        Path("STRUCTURE.md"),
        Path("PROJECT_INDEX.md"),
        Path("PROJECT_ORGANIZATION.md"),
        Path("API_REFERENCE.md"),
        Path("CHEAT_SHEET.md"),
    ]
    core_docs = [p for p in core_priority if p in top_level]

    reports = [
        p
        for p in top_level
        if p not in set(start_here_priority)
        and p not in set(core_priority)
        and p.name != "DOCUMENTATION_INDEX.md"
    ]

    module_docs = in_exact_dirs(files, {"api", "core_domain", "finance", "life-sprint-frontend"})
    docs_folder = [p for p in in_prefix(files, "docs") if "legacy-root-notes" not in p.as_posix()]
    legacy_notes = in_prefix(files, "docs/legacy-root-notes")

    quick_nav = [
        Path("START_HERE.md"),
        Path("QUICKSTART.md"),
        Path("API_REFERENCE.md"),
        Path("PROJECT_INDEX.md"),
        Path("life-sprint-frontend/README.md"),
    ]
    quick_nav = [p for p in quick_nav if p in files]

    return (
        "# Life Sprint Documentation Index\n\n"
        "This file is auto-generated by tools/update_documentation_index.py.\n"
        "Run: `python tools/update_documentation_index.py`\n\n"
        "## Quick Navigation\n\n"
        f"{to_md_list(quick_nav)}\n"
        "## 1) Start Here\n\n"
        f"{to_md_list(start_here)}\n"
        "## 2) Core Project Documentation\n\n"
        f"{to_md_list(core_docs)}\n"
        "## 3) Recent Work & Status Reports\n\n"
        f"{to_md_list(reports)}\n"
        "## 4) Module-Level READMEs\n\n"
        f"{to_md_list(module_docs)}\n"
        "## 5) Main Docs Folder\n\n"
        f"{to_md_list(docs_folder)}\n"
        "## 6) Archived / Legacy Notes\n\n"
        f"{to_md_list(legacy_notes)}\n"
        "## 7) Maintenance Rule\n\n"
        "When adding a new `.md` file, rerun the generator to refresh this index.\n"
    )


def main() -> None:
    files = rel_md_files()
    OUT.write_text(render(files), encoding="utf-8")
    print(f"Updated {OUT.relative_to(ROOT)} with {len(files)} markdown links.")


if __name__ == "__main__":
    main()
